/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.15
 * Generated at: 2026-04-15 06:50:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.example.User;

public final class employeeDashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.example.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
 
    User user = (User) session.getAttribute("user");
	if (user == null || !"employee".equalsIgnoreCase(user.getRole())) {
        response.sendRedirect("login.jsp?msg=Access denied!");
        return;
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<title>EmployeeApp</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\"></head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("	<div class=\"navbar\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<a href=\"index.jsp\" class=\"navbar-brand\">Employee Management</a>\n");
      out.write("			<ul class=\"navbar-nav\">\n");
      out.write("				<li class=\"nav-item\"><a href=\"logout.jsp\" class=\"nav-link\">\n");
      out.write("						<i class=\"fas fa-sign-out-alt\"></i> Logout\n");
      out.write("				</a></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<div class=\"card page-panel\">\n");
      out.write("			<span class=\"section-kicker\"><i class=\"fas fa-user\"></i> Employee workspace</span>\n");
      out.write("			<h1 class=\"hero-title\">Welcome, ");
      out.print( user.getName() );
      out.write("!</h1>\n");
      out.write("			<p class=\"hero-copy mb-3\">Your profile is ready. This dashboard keeps your account details visible without overwhelming you with unrelated controls.</p>\n");
      out.write("			<p class=\"mb-4\">Access level: <span class=\"badge bg-primary\">Employee</span></p>\n");
      out.write("\n");
      out.write("			<div class=\"feature-grid mb-4 mt-0 grid-2\">\n");
      out.write("				<div class=\"feature-card\">\n");
      out.write("					<i class=\"fas fa-envelope fa-2x\"></i>\n");
      out.write("					<h3>Email contact</h3>\n");
      out.write("					<p>");
      out.print( user.getEmail() );
      out.write("</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"feature-card\">\n");
      out.write("					<i class=\"fas fa-lock fa-2x\"></i>\n");
      out.write("					<h3>Protected access</h3>\n");
      out.write("					<p>Access is filtered by role, so only employee-safe options appear here.</p>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"card mb-4\">\n");
      out.write("				<h3 class=\"mb-3\"><i class=\"fas fa-user\"></i> Your Profile</h3>\n");
      out.write("				<ul class=\"list-unstyled\">\n");
      out.write("					<li class=\"mb-2\"><strong>Name:</strong> ");
      out.print( user.getName() );
      out.write("</li>\n");
      out.write("					<li class=\"mb-2\"><strong>Email:</strong> ");
      out.print( user.getEmail() );
      out.write("</li>\n");
      out.write("					<li><strong>Role:</strong> <span class=\"badge bg-primary\">Employee</span></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"text-center\">\n");
      out.write("				<a href=\"logout.jsp\" class=\"btn btn-danger\"><i class=\"fas fa-sign-out-alt\"></i> Logout</a>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
