/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.15
 * Generated at: 2026-04-15 06:47:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<title>EmployeeApp</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\"></head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"navbar\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<a href=\"index.jsp\" class=\"navbar-brand\">Employee Management</a>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"page-shell\">\n");
      out.write("		<div class=\"auth-shell auth-shell-single\">\n");
      out.write("			<div class=\"card auth-panel\">\n");
      out.write("				<span class=\"section-kicker\"><i class=\"fas fa-user-plus\"></i> Create account</span>\n");
      out.write("				<h2 class=\"mb-3\">Start with a clean employee profile</h2>\n");
      out.write("				<p class=\"hero-copy mb-4\">New users default to employee access. If your workspace has not been initialized yet, you can optionally bootstrap the first manager account here.</p>\n");
      out.write("				");

					String signupSuccess = request.getParameter("success");
					String signupError = request.getParameter("error");
					if (signupSuccess != null && !signupSuccess.trim().isEmpty()) {
				
      out.write("\n");
      out.write("					<div class=\"alert alert-success\">");
      out.print( signupSuccess );
      out.write("</div>\n");
      out.write("				");

					}
					if (signupError != null && !signupError.trim().isEmpty()) {
				
      out.write("\n");
      out.write("					<div class=\"alert alert-danger\">");
      out.print( signupError );
      out.write("</div>\n");
      out.write("				");

					}
				
      out.write("\n");
      out.write("				<form action=\"SignupServlet\" method=\"post\">\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"name\">Name</label>\n");
      out.write("						<input type=\"text\" id=\"name\" name=\"name\" class=\"form-control\" required>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"email\">Email</label>\n");
      out.write("						<input type=\"email\" id=\"email\" name=\"email\" class=\"form-control\" required>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label for=\"password\">Password</label>\n");
      out.write("						<input type=\"password\" id=\"password\" name=\"password\" class=\"form-control\" required>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<label>Role</label>\n");
      out.write("						<p class=\"form-control-plaintext mb-2\">Employee accounts are the default. Manager setup is only available before the first manager exists.</p>\n");
      out.write("						<div class=\"form-check\">\n");
      out.write("							<input class=\"form-check-input\" type=\"checkbox\" id=\"managerSetup\" name=\"managerSetup\">\n");
      out.write("							<label class=\"form-check-label\" for=\"managerSetup\">Create this account as the initial manager</label>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div class=\"action-row\">\n");
      out.write("						<button type=\"submit\" class=\"btn btn-success\">\n");
      out.write("							<i class=\"fas fa-user-plus\"></i> Sign Up\n");
      out.write("						</button>\n");
      out.write("						<a href=\"login.jsp\" class=\"btn btn-primary\">Already have an account?</a>\n");
      out.write("					</div>\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
